### ISSUE TITLE
portal access

### ISSUE THREAD

**Issue by spathakamuri11** [spathakamuri11/Devops#1]
user needs to be added to the group
![ajat-solo6](https://user-images.githubusercontent.com/78914477/107645540-ce532c80-6c46-11eb-9be2-a0deaa870b5a.jpg)

**Comment by bipeensinha** [comment]
i am working on this issue

**Comment by spathakamuri11** [comment]
please keep me posted

**Comment by bipeensinha** [comment]
ok sir issue has benn fixed
![Uploading a.png…]()

**Comment by spathakamuri11** [comment]
thank you
